### ISSUE TITLE
Migrate to gRPC may improve performance, size and communication?

### ISSUE THREAD

**Issue by naomijub** [naomijub/wooridb#128]
@otaviopace ???

**Comment by otaviopace** [comment]
Honestly I need to read the current implementation to see if this is viable.

There is a consideration about gRPC which is that this protocol on any change of the format (eg: field change) the requests will start to fail because it is all positional and calculated on size.

**Comment by naomijub** [comment]
https://github.com/naomijub/wooridb/pull/137

**Comment by naomijub** [comment]
So today I tested how long does ti take to respond a query without passing to a query itsenf. The current value with actix_web is:
```
- `select_all` 20 entities  time:   [23.692 ms 24.183 ms 24.690 ms]
- `select_all` 10 entities  time:   [22.018 ms 22.301 ms 22.586 ms]
- `select_all` 1 entity     time:   [19.963 ms 20.679 ms 21.412 ms]
```

while this result for an empty query took `[19.872 ms 20.888 ms 21.920 ms]` which s weird because it is greater than the create entity (on mac) `[15.269 ms 15.332 ms 15.396 ms]`

If this articles are true, it would be possible to reduce the request time from 30% to 50% with gRPC:
https://dev.to/plutov/benchmarking-grpc-and-rest-in-go-565
https://medium.com/@EmperorRXF/evaluating-performance-of-rest-vs-grpc-1b8bdf0b22da

**Comment by naomijub** [comment]
I imagine GraphQL will take more or less the same time as rest and will not have support for HashMap of types in the response? Also juniper is no async which leaves us only with https://github.com/async-graphql/async-graphql
