### ISSUE TITLE
json

### ISSUE THREAD

**Issue by sc13-bioinf** [naomijub/wooridb#172]
Hi, I am writing a client library for wooridb. It would be great to be able to use vanilla serde_json::from_str. The custom DateTime seems to require me to implement my own deserialiser. Or am I missing something? Still trying to get my head around serde etc.

**Comment by naomijub** [comment]
You probably need chronological with derive feature enabled. My computer is in support, so I can't take a deeper look, but if you could try this it would probably help. 

For more info check chrono crate in woori's cargo.toml

**Comment by sc13-bioinf** [comment]
So I think what you actually see is the wql enum Types::DateTime. The time itself is serialised as a string. It then becomes a question of being able to serialise the enum in some kind of json style (so self describing). I gave this a try, but then bincode was not happy. That got me thinking that perhaps there should be different serialisation for transport vs storage and use serde transcode.

**Comment by naomijub** [comment]
My computer just came back, I will check the PR and the Issue tomorrow

**Comment by naomijub** [comment]
Before, is your chrono supporting serde?
`chrono = { version = "0.4.19", features = ["serde"] }`

**Comment by naomijub** [comment]
Yep, this (`chrono = { version = "0.4.19", features = ["serde"] }`) works for this issue
